INSERT INTO public.customers (name, phone, address) VALUES ('Aman Asati', '9425469983', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Bhupendra Dhakad', '8516990388', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Dr. Gaur', '9425818919', 'Agarwal Nagar');
INSERT INTO public.customers (name, phone, address) VALUES ('Deshmukh ji', '9300815581', 'Agarwal Nagar');
INSERT INTO public.customers (name, phone, address) VALUES ('Sahil Chauhan', '7509642444', 'Agarwal Nagar');
INSERT INTO public.customers (name, phone, address) VALUES ('Gajanand Sahu', '9977000271', NULL);
INSERT INTO public.customers (name, phone, address) VALUES ('Harindar Patel ji', '8225889881', NULL);     
INSERT INTO public.customers (name, phone, address) VALUES ('Vmesh ishai', '8962626362', 'Sterling Globs');
INSERT INTO public.customers (name, phone, address) VALUES ('awadh', '9425665454', 'Gopal Nagar');        
INSERT INTO public.customers (name, phone, address) VALUES ('Satendra Singh', '9302651542', 'Gopal Nagar');
INSERT INTO public.customers (name, phone, address) VALUES ('Yashwant Atulkar', '7869557838', 'BDA');     
INSERT INTO public.customers (name, phone, address) VALUES ('Arora ji', '8319662298', 'Shivlok Green');   
INSERT INTO public.customers (name, phone, address) VALUES ('Iqbal quadari', '9522557786', 'Prabhatam');  
INSERT INTO public.customers (name, phone, address) VALUES ('Arish', '9340647733', NULL);
INSERT INTO public.customers (name, phone, address) VALUES ('Dharmendra', '7489822242', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Saurabh', '7869178474', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Narendra Tiwari', '8839387117', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Manoj Vaishnav', '8949558176', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Shbhash Singh', '9813580981', NULL);
INSERT INTO public.customers (name, phone, address) VALUES ('Yogesh ji', '9826647092', NULL);
INSERT INTO public.customers (name, phone, address) VALUES ('Girja Shankar ji', '7976590814', NULL);      
INSERT INTO public.customers (name, phone, address) VALUES ('Sunil Ekka ji', '9425654563', 'Indraprast'); 
INSERT INTO public.customers (name, phone, address) VALUES ('Uttam', '9826412880', 'Gopal Nagar');        
INSERT INTO public.customers (name, phone, address) VALUES ('Saurabh', '9981747863', 'Gopal Nagar');      
INSERT INTO public.customers (name, phone, address) VALUES ('Adarsh Chouksey', '8435052506', NULL);       
INSERT INTO public.customers (name, phone, address) VALUES ('Pawan ji', '9993957352', 'Katara Hills');    
INSERT INTO public.customers (name, phone, address) VALUES ('Kajal Vishwakarma', '7987971476', 'Park City');
INSERT INTO public.customers (name, phone, address) VALUES ('Akhilesh', '9981244609', 'Bilkhiria');       
INSERT INTO public.customers (name, phone, address) VALUES ('S.k. Tiwari Ji', '9303327773', 'Transport Nagar');
INSERT INTO public.customers (name, phone, address) VALUES ('Shalendra', '9617757067', 'Rajdhani Parisor');
INSERT INTO public.customers (name, phone, address) VALUES ('MuniDeen', '9981574991', 'Rajdhani Parisor');
INSERT INTO public.customers (name, phone, address) VALUES ('Neha Singh', '7089205778', NULL);
INSERT INTO public.customers (name, phone, address) VALUES ('Nitish Sinha', '9109909181', 'Khajum');      
INSERT INTO public.customers (name, phone, address) VALUES ('Sharad Parasar', '7049331490', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Shalesh ji', '7869995052', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Raui ji', '9783878861', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Dinesh Solanki', '9926436554', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Arun Solanki', '9926743265', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Shahid ji', '8463899176', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Seepchand ji', '9024250821', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Mishra ji', '9074514874', 'Vivekanand Coloney');
INSERT INTO public.customers (name, phone, address) VALUES ('Sonu kumar', '8947815340', NULL);
INSERT INTO public.customers (name, phone, address) VALUES ('G.S. Rajput', '9303960307', NULL);
INSERT INTO public.customers (name, phone, address) VALUES ('Shubhash Jain', '9644229033', 'Awadhpuri');  
INSERT INTO public.customers (name, phone, address) VALUES ('Arvind Kumar Pandey', '9977338702', 'Awadhpuri');
INSERT INTO public.customers (name, phone, address) VALUES ('Sandeep Kumar Namdeo', '9425451218', 'Awadhpuri');
INSERT INTO public.customers (name, phone, address) VALUES ('Ankit Purohit', '9926220395', 'Anjali Vihar');
INSERT INTO public.customers (name, phone, address) VALUES ('Gupteshwar Mishra ji', '7000713193', 'Awadhpuri');
INSERT INTO public.customers (name, phone, address) VALUES ('Santosh Sahu', '8989661129', 'Awadhpuri');   
INSERT INTO public.customers (name, phone, address) VALUES ('Surekha Madam', '8305991724', 'Anjali Vihar');
INSERT INTO public.customers (name, phone, address) VALUES ('Asish Singh', '7354449377', 'Gopal Nagar');  
INSERT INTO public.customers (name, phone, address) VALUES ('Gopal Pradhan ji', '8989161161', 'Awadhpuri');